In [8]:
import numpy as np

# **Shape And Dimension**

In [9]:
a = np.array([1,1,2,3,4,5])
b = a.shape
print(b)

(6,)


In [10]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)])
b = a.shape
print(b)

(2, 6)


In [11]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)])
a.ndim #dimension

2

In [12]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
a_3d = a.reshape(2,2, 3, 2)

print(a_3d)
print(a_3d.ndim) #dimension

[[[[ 1  1]
   [ 2  3]
   [ 4  5]]

  [[ 1  3]
   [ 5  4]
   [67  7]]]


 [[[ 1  2]
   [ 8  4]
   [ 6  7]]

  [[ 1  2]
   [ 8  4]
   [ 6  7]]]]
4


In [13]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]
b = np.array(a)
print(b.reshape(7,5)) # Reshape

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [14]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
a.T  # Transpose

array([[ 1,  1,  1],
       [ 1,  3,  2],
       [ 2,  5,  8],
       [ 3,  4,  4],
       [ 4, 67,  6],
       [ 5,  7,  7]])

In [15]:
a = np.arange(60).reshape(12,5)
a.transpose() # Transpose

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [16]:
a = np.arange(60).reshape(12,5)
a.reshape(5,3,4) # Reshape

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [17]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]

b = np.array(a)
b.flatten() # this is convert to the one dimention


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# **Data Type Change**

In [18]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)], dtype= float)
print(a)

[[ 1.  1.  2.  3.  4.  5.]
 [ 1.  3.  5.  4. 67.  7.]]


In [19]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)], dtype= str)
print(a)

[['1' '1' '2' '3' '4' '5']
 ['1' '3' '5' '4' '67' '7']]


In [20]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7)], dtype= np.int32)
print(a)

[[ 1  1  2  3  4  5]
 [ 1  3  5  4 67  7]]


# **Zero Array Create**

In [21]:
# create the numpy of zeros
x = np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# **Create Array for perticular values**

In [69]:
# create the numpy of perticular values
x = np.full((5,7),1)
print(x)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


# **Identity Matrix**

In [23]:
# create an identity matrix
x = np.eye(4) # this is create the array and dignar values are 1 and remaining are 0
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **Create Random Array**

In [24]:
# random integer value
x = np.random.randint(1,100,(3,4))
print(x)

[[45  1 79 65]
 [59 38 88  7]
 [15 67 19 50]]


In [25]:
np.random.rand(5) # random number generate  mean = 0, std = 1


array([0.47651774, 0.62904295, 0.66569606, 0.28926062, 0.41299446])

In [26]:
np.random.normal(5, 2, (3, 4))  # mean=5, std=2


array([[2.5331264 , 5.81312475, 6.75492149, 4.92944731],
       [1.74236398, 5.15954718, 3.57506467, 7.97907641],
       [6.97159169, 5.87743668, 6.76279825, 2.66876506]])

In [27]:
np.random.random((3, 4)) # Between 0 to 1

array([[0.5657603 , 0.07077871, 0.80659483, 0.16130628],
       [0.06507871, 0.08762186, 0.90440039, 0.42226237],
       [0.19692234, 0.05361851, 0.73726907, 0.4812672 ]])

In [28]:
np.random.uniform(1, 100, size=(3, 4)) # random number value

array([[77.4662983 , 77.45436497, 80.70565835, 76.99274493],
       [49.63493885, 39.93794586, 74.57062365, 63.99870043],
       [41.47485186, 96.69935949, 12.44050595, 14.3713845 ]])

In [29]:
a = np.random.choice(['apple', 'banana', 'cherry'], size=(3, 4)) #generate random string
print(a)


[['apple' 'cherry' 'cherry' 'banana']
 ['cherry' 'cherry' 'apple' 'apple']
 ['apple' 'cherry' 'apple' 'apple']]


In [71]:
# array of evenly spaced values --> specifying the number of values required
x = np.linspace(10,30,5)
print(x)

[10. 15. 20. 25. 30.]


In [72]:
# array of evenly spaced values --> specifying the step
x = np.arange(10,50,9)
print(x)

[10 19 28 37 46]


# **Convert List to the Array**

In [32]:
#  convert the list to the np array
x = [1,2,3,4,5,6,7,8,9]
y = np.asarray(x)
print(y)
print(type(y))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


# **Count Element**

In [33]:
a = [[2 ,2 ,2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2],
 [2, 2, 2, 2, 2, 2, 2]]
b = np.array(a)
print(b.size) # count the element

35


# **Arithmetic Operations**

In [34]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
print(a)
print(b)
print("SUM: ",a + b)
print("SUB: ",a - b)
print("MULTIPICATION: ",a * b)
print("DIV: ",b / a)
print("FLOOR DIVISION: ",b // a)
print("MODULO: ",b % a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
SUM:  [[12 14 16]
 [18 20 22]
 [24 26 28]]
SUB:  [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
MULTIPICATION:  [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
DIV:  [[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
FLOOR DIVISION:  [[11  6  4]
 [ 3  3  2]
 [ 2  2  2]]
MODULO:  [[0 0 1]
 [2 0 4]
 [3 2 1]]


In [35]:
a = np.arange(1,10).reshape(3,3)
np.subtract(a,3) # Subtract

array([[-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [36]:
a = np.arange(1,10).reshape(3,3)
np.sum(a) # Sum

np.int64(45)

In [37]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sum(a, axis=0) # Column-wise sum

array([ 3,  6, 15, 11, 77, 19])

In [38]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sum(a, axis=1) # Row-wise sum

array([16, 87, 28])

# **Sort Array**

In [39]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.sort(a) #Sort Array

array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  4,  5,  7, 67],
       [ 1,  2,  4,  6,  7,  8]])

# **Unique Value Find**

In [40]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.unique(a) #unique Array

array([ 1,  2,  3,  4,  5,  6,  7,  8, 67])

# **Condition Apply**

In [41]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
a[a < 50] = 0 # replace value
print(a)


[[ 0  0  0  0  0  0]
 [ 0  0  0  0 67  0]
 [ 0  0  0  0  0  0]]


In [74]:
a = np.array([1, 2, 3, 4, 5])

result = np.where(a % 2 == 0, a * 10, a)
print(result)

[ 1 20  3 40  5]


# **Split Array**

In [43]:
a = np.arange(1,37).reshape(6,6)
print(a)
np.hsplit(a,3) # horizontal split

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [44]:
a = np.arange(1,37).reshape(6,6)
print(a)
np.split(a,3, axis=1) # horizontal split

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [45]:
a = np.arange(1,37).reshape(6,6)
print(a)
np.split(a,2, axis=0) # vertical split

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [46]:
a = np.arange(1,37).reshape(6,6)
print(a)
np.vsplit(a,3) # vertical split

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [47]:
a = np.arange(1,37).reshape(6,6)
np.array_split(a, 4, axis =1) #unequal horizontal split

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]]),
 array([[ 6],
        [12],
        [18],
        [24],
        [30],
        [36]])]

In [48]:
a = np.arange(1,37).reshape(6,6)
np.array_split(a, 4, axis =0) #unequal vertical split

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36]])]

# **Stack Array**

In [49]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7)])

np.vstack((a,b)) # vertical stack array


array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  5,  4, 67,  7],
       [ 1,  2,  8,  4,  6,  7],
       [ 1, 34, 10,  3, 64,  5],
       [ 1, 33, 25, 42, 67,  7]])

In [50]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])

np.hstack((a,b)) # horizontal stack array

array([[ 1,  1,  2,  3,  4,  5,  1, 34, 10,  3, 64,  5],
       [ 1,  3,  5,  4, 67,  7,  1, 33, 25, 42, 67,  7],
       [ 1,  2,  8,  4,  6,  7, 11, 23, 38,  4, 65,  7]])

In [51]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.clip(a,5,100) # it is doing like the conver the all lower number to this perticular number


array([[ 5,  5,  5,  5,  5,  5],
       [ 5,  5,  5,  5, 67,  7],
       [ 5,  5,  8,  5,  6,  7],
       [ 5,  5,  8,  5,  6,  7]])

In [52]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.where(a > 7, 1, 0) # where condition

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

# **Mathematics Calculation**

In [53]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10),(3,64,5), (1,33,25),(42,67,7), (11,23,38),(4,65,7)])

np.dot(a,b) #dot array \(C_{i,j}=\sum _{k=0}^{n-1}a_{i,k}\cdot b_{k,j}\)

array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])

In [54]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.std(a) # Standard deviation

np.float64(14.646977524980501)

In [55]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.var(a) # Variance

np.float64(214.53395061728395)

In [56]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.argmax(a) # index of max

np.int64(10)

In [57]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
np.argmin(a) # index of min

np.int64(0)

In [58]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7),(1,2,8,4,6,7)])
b =(a - a.min()) / (a.max() - a.min())
print(b) # normalization

[[0.         0.         0.01515152 0.03030303 0.04545455 0.06060606]
 [0.         0.03030303 0.06060606 0.04545455 1.         0.09090909]
 [0.         0.01515152 0.10606061 0.04545455 0.07575758 0.09090909]
 [0.         0.01515152 0.10606061 0.04545455 0.07575758 0.09090909]]


In [59]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10),(3,64,5), (1,33,25),(42,67,7), (11,23,38),(4,65,7)])
np.matmul(a,b) # same as dot function (multiplication)


array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])

In [60]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.eig(a) #Eigen values


EigResult(eigenvalues=array([3967.73671301,   33.27538674, -625.01209975]), eigenvectors=array([[-0.21434062, -0.96924162,  0.41300514],
       [-0.90913762,  0.12838535, -0.65464231],
       [-0.35710906,  0.20997116,  0.63314311]]))

In [61]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.inv(a) #Inverse matrix

array([[ 0.02635725,  0.0007174 , -0.017495  ],
       [-0.00327707, -0.00033058,  0.00345016],
       [-0.00587308,  0.00043188,  0.00267764]])

In [62]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.linalg.det(a) #Determinate

np.float64(-82519081.00000006)

In [63]:
a = np.array([[ 196,  782,  273],
       [ 948, 2655, 2773],
       [ 277, 1287,  525]])
np.percentile(a,87.5) #Percentile

np.float64(2655.0)

In [64]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])
np.corrcoef(a,b) #Correlation

array([[1.        , 0.46051453, 0.66955589, 0.16217309, 0.23510743,
        0.11698707],
       [0.46051453, 1.        , 0.2985275 , 0.86838604, 0.76880568,
        0.84355184],
       [0.66955589, 0.2985275 , 1.        , 0.09728206, 0.20483487,
        0.38224333],
       [0.16217309, 0.86838604, 0.09728206, 1.        , 0.80113065,
        0.85602093],
       [0.23510743, 0.76880568, 0.20483487, 0.80113065, 1.        ,
        0.70006163],
       [0.11698707, 0.84355184, 0.38224333, 0.85602093, 0.70006163,
        1.        ]])

In [65]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
b = np.array([(1,34,10,3,64,5), (1,33,25,42,67,7), (11,23,38,4,65,7)])
np.cov(a,b) #Covariance

array([[  2.66666667,  19.4       ,   3.06666667,   6.6       ,
          9.26666667,   4.46666667],
       [ 19.4       , 665.5       ,  21.6       , 558.3       ,
        478.7       , 508.8       ],
       [  3.06666667,  21.6       ,   7.86666667,   6.8       ,
         13.86666667,  25.06666667],
       [  6.6       , 558.3       ,   6.8       , 621.1       ,
        481.9       , 498.8       ],
       [  9.26666667, 478.7       ,  13.86666667, 481.9       ,
        582.56666667, 395.06666667],
       [  4.46666667, 508.8       ,  25.06666667, 498.8       ,
        395.06666667, 546.66666667]])

# **Numpy Save And Load**

In [66]:
a = np.array([(1,1,2,3,4,5), (1,3,5,4,67,7), (1,2,8,4,6,7)])
np.save("data.npy", a) # save Array

In [67]:
np.load("data.npy") # Load File

array([[ 1,  1,  2,  3,  4,  5],
       [ 1,  3,  5,  4, 67,  7],
       [ 1,  2,  8,  4,  6,  7]])

# **Broadcasting**

In [68]:
a = np.array([(1,1,2)])
a + np.array([3,2,1]) #Broadcasting

array([[4, 3, 3]])